import React from "react";

export const ProductData = [
    {
        image: "Image1",
        name: "Áo khoác nam Sges mùa hè ",
        category: "asd á dá dá dá knsdk jbsdkj b",
        price: "100000",
        sale: "90000",
        quantity: "100",
        view: "4023",
    },
    {
        image: "Image1",
        name: "Áo khoác nam Sges mùa hè ",
        category: "asd á dá dá dá knsdk jbsdkj b",
        price: "100000",
        sale: "90000",
        quantity: "100",
        view: "4023",
    },
    {
        image: "Image1",
        name: "Áo khoác nam Sges mùa hè ",
        category: "asd á dá dá dá knsdk jbsdkj b",
        price: "100000",
        sale: "90000",
        quantity: "100",
        view: "4023",
    },
    {
        image: "Image1",
        name: "Áo khoác nam Sges mùa hè ",
        category: "asd á dá dá dá knsdk jbsdkj b",
        price: "100000",
        sale: "90000",
        quantity: "100",
        view: "4023",
    },
    {
        image: "Image1",
        name: "Áo khoác nam Sges mùa hè ",
        category: "asd á dá dá dá knsdk jbsdkj b",
        price: "100000",
        sale: "90000",
        quantity: "100",
        view: "4023",
    },
    {
        image: "Image1",
        name: "Áo khoác nam Sges mùa hè ",
        category: "asd á dá dá dá knsdk jbsdkj b",
        price: "100000",
        sale: "90000",
        quantity: "100",
        view: "4023",
    },
    {
        image: "Image1",
        name: "Áo khoác nam Sges mùa hè ",
        category: "asd á dá dá dá knsdk jbsdkj b",
        price: "100000",
        sale: "90000",
        quantity: "100",
        view: "4023",
    },
    {
        image: "Image1",
        name: "Áo khoác nam Sges mùa hè ",
        category: "asd á dá dá dá knsdk jbsdkj b",
        price: "100000",
        sale: "90000",
        quantity: "100",
        view: "4023",
    },
];
